# Generated by Django 4.2.5 on 2023-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenturl',
            name='title',
            field=models.TextField(default='Subject Video'),
        ),
    ]
