# Generated by Django 4.2.5 on 2023-10-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contenturl_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=33)),
                ('skills', models.CharField(max_length=899)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contenturl',
            name='subject_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='api.subject'),
        ),
        migrations.DeleteModel(
            name='SubjectContent',
        ),
    ]
