# Generated by Django 4.2.5 on 2023-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subject_alter_contenturl_subject_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=33, unique=True),
        ),
    ]
