# Generated by Django 4.2.5 on 2023-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subject_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default=models.CharField(db_index=True, max_length=33, unique=True), max_length=899),
        ),
    ]
