# Generated by Django 4.2.5 on 2023-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenturl',
            name='url',
            field=models.CharField(default='Subject Video', max_length=33),
        ),
    ]
