# Generated by Django 4.2.5 on 2023-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_contenturl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenturl',
            name='url',
            field=models.CharField(default='rdwz7QiG0lk?si=_uI8RAN_tdMH8OCS', max_length=899),
        ),
    ]
