# Generated by Django 4.2.5 on 2023-10-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_contenturl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenturl',
            name='title',
            field=models.CharField(default='Video: <django.db.models.query_utils.DeferredAttribute object at 0x000001E4DC5F1550>', max_length=899),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='skills',
            field=models.CharField(blank=True, max_length=899),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(db_index=True, max_length=899, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=899),
        ),
    ]
