# Generated by Django 4.2.5 on 2023-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_contenturl_title_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenturl',
            name='title',
            field=models.CharField(default=' ', max_length=899),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default=' ', max_length=899),
        ),
    ]
